### ISSUE TITLE
Preprocessor does not work with feature files that contain spaces in the feature file name

### ISSUE THREAD

**Issue by csrenato** [atdd-bdd/preprocessor#1]
Hi.

In our team we are using feature files that contain spaces (they have somewhat long names that shortly describe the feature they are containing).

The preprocessor is doing its job, but it does not work with feature files that contain spaces.

Example file names:
test.feature
test with spaces.feature

First one works like a charm:

java -jar preprocessor.jar -featurein featurein -featureout featureout -include featurein

Configuration is:
Output Feature Path: featureout
Input Feature Path: featurein
Include Path: featurein
Cucumber Preprocessor
This jar includes the following packages
commons-cli-1.4.jar
commons-csv-1.5.jar
cucumber-core-2.3.1.jar
cucumber-html-0.2.3.jar
cucumber-java-2.3.1.jar
cucumber-junit-2.3.1.jar
cucumber-jvm-deps-1.0.6.jar
EvalEx-2.0.jar
gherkin-5.0.0.jar
joda-convert-2.0.1.jar
joda-time-2.9.9.jar
junit-4.7.jar
mxparser.jar
tag-expressions-1.1.1.jar
Feature files are:
Files are featurein/test.feature
Reading CSV

-------

The second one not:

java -jar preprocessor.jar -featurein featurein -featureout featureout -include featurein

Configuration is:
Output Feature Path: featureout
Input Feature Path: featurein
Include Path: featurein
Cucumber Preprocessor
This jar includes the following packages
commons-cli-1.4.jar
commons-csv-1.5.jar
cucumber-core-2.3.1.jar
cucumber-html-0.2.3.jar
cucumber-java-2.3.1.jar
cucumber-junit-2.3.1.jar
cucumber-jvm-deps-1.0.6.jar
EvalEx-2.0.jar
gherkin-5.0.0.jar
joda-convert-2.0.1.jar
joda-time-2.9.9.jar
junit-4.7.jar
mxparser.jar
tag-expressions-1.1.1.jar
***ERROR*** Bad Pathname after adding: test with spaces.feature
Feature files are:
Files are featurein
***ERROR*** Bad Pathname after adding:
***ERROR*** Bad Pathname after adding:
***ERROR*** Unable to read /Users/curicren/testnifolder/preprocessor/localtest/featurein featurein (Is a directory)
***ERROR*** Exiting on error

**Comment by atdd-bdd** [comment]
Fixed for feature file names.
